FROM node:16-alpine

WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./packages/client/package*.json ./packages/client/
COPY ./packages/shared/package*.json ./packages/shared/

RUN npm ci -w packages/client

COPY ./packages/client ./packages/client
COPY ./packages/shared ./packages/shared

ARG CHAT_APP_API_URL
ENV REACT_APP_API_URL=${CHAT_APP_API_URL}

RUN npm run build -w packages/client

EXPOSE 3000

CMD ["npx", "serve", "packages/client/build"]