FROM node:16-alpine

WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./packages/api/package*.json ./packages/api/
COPY ./packages/shared/package*.json ./packages/shared/

RUN npm ci -w packages/api

COPY ./packages/api ./packages/api
COPY ./packages/shared ./packages/shared

RUN npm run build -w packages/api

EXPOSE 8800

CMD [ "node", "packages/api/dist/app.js" ]